version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: DOCKER_USERNAME
    DOCKER_PASSWORD: DOCKER_PASSWORD
  variables:
    DOCKER_REGISTRY: "docker.io"
    PHP_IMAGE: cb-php
    PHP_TEST_IMAGE: cb-php-test
    TEST_JOB_NAME: TEST-PHP-CICD

phases:
  pre_build:
    commands:
      - echo "Pre Build"
      - python ./scripts/codebuild_helper.py --registry_login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD --registry $DOCKER_REGISTRY
    finally:
      - echo "Finally Pre Build"
  build:
    commands:
      - echo "Build"
      - python ./scripts/codebuild_helper.py --build_docker --image_name $DOCKER_USERNAME/$PHP_IMAGE --tags_list latest $CODEBUILD_RESOLVED_SOURCE_VERSION --dockerfile Dockerfile
      - python ./scripts/codebuild_helper.py --build_docker --image_name $DOCKER_USERNAME/$PHP_TEST_IMAGE --tags_list latest $CODEBUILD_RESOLVED_SOURCE_VERSION --dockerfile Test.Dockerfile --build_arg "base_image=$DOCKER_USERNAME/$PHP_IMAGE:latest"
    finally:
      - echo "Finally Build"
  post_build:
    commands:
      - python ./scripts/codebuild_helper.py --trigger_codebuild --project_name $TEST_JOB_NAME --image_override $DOCKER_USERNAME/$PHP_TEST_IMAGE:latest
    finally:
      - echo "Finally Post Build"
