version: 0.2

env:
  variables:
    PROJECT_NAME: DEPLOY-PHP-CICD

phases:
  pre_build:
    commands:
      - echo "Pre Build"
    finally:
      - echo "Finally Pre Build"
  build:
    commands:
      - echo "Build"
      - echo "To start the Deploy Job execute"
      - echo "aws codebuild start-build --project-name $PROJECT_NAME"
    finally:
      - echo "Finally Build"
  post_build:
    commands:
      - echo "Post Build"
    finally:
      - echo "Finally Post Build"
