version: 0.2

env:
  variables:
    CHATOPS_JOB_NAME: CHATOPS-PHP-CICD
    FAIL: NO_ERROR

phases:
  pre_build:
    commands:
      - echo "Pre Build"
    finally:
      - echo "Finally Pre Build"
  build:
    commands:
      - echo "Build"
      - echo Unit Test
      - phpunit --bootstrap ./src/Calculator.php ./tests/CalculatorTest.php
      - phpunit --bootstrap ./src/Email.php ./tests/EmailTest.php
      - echo Integration Test
      - phpunit --bootstrap ./src/Music.php ./tests/MusicIntegrationTest.php
      - echo Functional Test
      - phpunit --bootstrap ./src/Music.php ./tests/MusicFunctionalTest.php
    finally:
      - echo "Finally Build"
  post_build:
    commands:
      - python3 ./scripts/codebuild_helper.py --trigger_codebuild --project_name $CHATOPS_JOB_NAME
    finally:
      - echo "Finally Post Build"
